<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Readme.md" Pack="true" PackagePath="\" />
    <PackageReference Include="CliWrap" Version="3.10.5" />
    <PackageReference Include="GnomeStack.Os.Release" Version="0.1.3" />
  </ItemGroup>

</Project>
